// RUN: %run_test hipify "%s" "%t" %hipify_args 3 --amap --skip-excluded-preprocessor-conditional-blocks --experimental %clang_args -D__CUDA_API_VERSION_INTERNAL -ferror-limit=500

// CHECK: #include <hip/hip_runtime.h>
#include <cuda_runtime.h>
#include <stdio.h>
// CHECK: #include "hiptensor.h"
#include "cutensor.h"
// CHECK-NOT: #include "hiptensor.h"

int main() {

    // CHECK: hiptensorStatus_t tensorStatus;
    // CHECK: hiptensorStatus_t tensorStatus_t;
    // CHECK-NEXT hiptensorStatus_t tensorStatus;
    // CHECK-NEXT hiptensorStatus_t TENSOR_STATUS_SUCCESS HIPTENSOR_STATUS_SUCCESS;
    // CHECK-NEXT hiptensorStatus_t TENSOR_STATUS_NOT_INITIALIZED HIPTENSOR_STATUS_NOT_INITIALIZED;
    // CHECK-NEXT hiptensorStatus_t TENSOR_STATUS_ALLOC_FAILED HIPTENSOR_STATUS_ALLOC_FAILED;
    // CHECK-NEXT hiptensorStatus_t TENSOR_STATUS_INVALID_VALUE HIPTENSOR_STATUS_INVALID_VALUE;
    // CHECK-NEXT hiptensorStatus_t TENSOR_STATUS_ARCH_MISMATCH HIPTENSOR_STATUS_ARCH_MISMATCH;
    // CHECK-NEXT hiptensorStatus_t TENSOR_STATUS_EXECUTION_FAILED HIPTENSOR_STATUS_EXECUTION_FAILED;
    // CHECK-NEXT hiptensorStatus_t TENSOR_STATUS_INTERNAL_ERROR HIPTENSOR_STATUS_INTERNAL_ERROR;
    // CHECK-NEXT hiptensorStatus_t TENSOR_STATUS_NOT_SUPPORTED HIPTENSOR_STATUS_NOT_SUPPORTED;
    // CHECK-NEXT hiptensorStatus_t TENSOR_STATUS_INSUFFICIENT_WORKSPACE HIPTENSOR_STATUS_INSUFFICIENT_WORKSPACE;
    // CHECK-NEXT hiptensorStatus_t TENSOR_STATUS_INSUFFICIENT_DRIVER HIPTENSOR_STATUS_INSUFFICIENT_DRIVER;
    // CHECK-NEXT hiptensorStatus_t TENSOR_STATUS_IO_ERROR HIPTENSOR_STATUS_IO_ERROR;
    cutensorStatus tensorStatus;
    cutensorStatus_t tensorStatus_t;
    cutensorStatus_t TENSOR_STATUS_SUCCESS = CUTENSOR_STATUS_SUCCESS;
    cutensorStatus_t TENSOR_STATUS_NOT_INITIALIZED CUTENSOR_STATUS_NOT_INITIALIZED;
    cutensorStatus_t TENSOR_STATUS_ALLOC_FAILED CUTENSOR_STATUS_ALLOC_FAILED;
    cutensorStatus_t TENSOR_STATUS_INVALID_VALUE CUTENSOR_STATUS_INVALID_VALUE;
    cutensorStatus_t TENSOR_STATUS_ARCH_MISMATCH CUTENSOR_STATUS_ARCH_MISMATCH;
    cutensorStatus_t TENSOR_STATUS_EXECUTION_FAILED CUTENSOR_STATUS_EXECUTION_FAILED;
    cutensorStatus_t TENSOR_STATUS_INTERNAL_ERROR CUTENSOR_STATUS_INTERNAL_ERROR;
    cutensorStatus_t TENSOR_STATUS_NOT_SUPPORTED CUTENSOR_STATUS_NOT_SUPPORTED;
    cutensorStatus_t TENSOR_STATUS_INSUFFICIENT_WORKSPACE CUTENSOR_STATUS_INSUFFICIENT_WORKSPACE;
    cutensorStatus_t TENSOR_STATUS_INSUFFICIENT_DRIVER CUTENSOR_STATUS_INSUFFICIENT_DRIVER;
    cutensorStatus_t TENSOR_STATUS_IO_ERROR CUTENSOR_STATUS_IO_ERROR;
}
