name: Issue Report
description: File a report for ROCm related issues on Linux and Windows. For issues pertaining to documentation or non-bug related, please open a blank issue located below.
title: "[HIPIFY][Issue] "

body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this report!

      You can acquire your OS, CPU, GPU (for filling out this report) with the following commands:

      Linux:
        echo "OS:" && cat /etc/os-release | grep -E "^(NAME=|VERSION=)";
        echo "CPU: " && cat /proc/cpuinfo | grep "model name" | sort --unique;
        echo "GPU:" && /opt/rocm/bin/rocminfo | grep -E "^\s*(Name|Marketing Name)";
        
      Windows:
         (Get-WmiObject Win32_OperatingSystem).Version
         (Get-WmiObject win32_Processor).Name
         (Get-WmiObject win32_VideoController).Name
- type: textarea
  attributes:
    label: Problem Description
    description: Describe the issue you encountered.
  validations:
    required: true
- type: input
  attributes:
    label: Operating System
    description: What is the name and version number of the OS?
    placeholder: "e.g. Ubuntu 22.04.3 LTS (Jammy Jellyfish), Windows 11"
  validations:
    required: true
- type: input
  attributes:
    label: CPU
    description: What CPU did you encounter the issue on?
    placeholder: "e.g. AMD Ryzen 9 9950X3D with Radeon Graphics"
  validations:
    required: false
- type: dropdown
  attributes:
    label: ROCm Version
    description: What version(s) of ROCm did you encounter the issue on?
    multiple: true
    options:
        - ROCm 6.3.1
        - ROCm 6.3.0
        - ROCm 6.2.4
        - ROCm 6.2.2
        - ROCm 6.2.1
        - ROCm 6.2.0
        - ROCm 6.1.2
        - ROCm 6.1.1
        - ROCm 6.1.0
        - ROCm 6.0.2
        - ROCm 6.0.0
        - ROCm 5.7.1
        - ROCm 5.7.0
        - ROCm 5.6.1
        - ROCm 5.6.0
        - ROCm 5.5.1
        - ROCm 5.5.0
        - ROCm 5.4.4
        - ROCm 5.4.3
        - ROCm 5.4.2
        - ROCm 5.4.1
        - ROCm 5.4.0
        - ROCm 5.3.3
        - ROCm 5.3.2
        - ROCm 5.3.1
        - ROCm 5.3.0
        - ROCm 5.2.3
        - ROCm 5.2.1
        - ROCm 5.2.0
        - ROCm 5.1.3
        - ROCm 5.1.1
        - ROCm 5.1.0
        - ROCm 5.0.2
        - ROCm 5.0.1
        - ROCm 5.0.0
  validations:
    required: true
- type: dropdown
  attributes:
    label: ROCm Component
    description: (Optional) If this issue relates to a specific ROCm component, it can be mentioned here.
    options:
      - Other
      - AMDMIGraphX
      - amdsmi
      - aomp
      - aomp-extras
      - clang-ocl
      - clr
      - composable_kernel
      - flang
      - half
      - HIP
      - hipBLAS
      - hipBLASLt
      - HIPCC
      - hipCUB
      - HIP-Examples
      - hipFFT
      - hipfort
      - HIPIFY
      - hipOther
      - hipRAND
      - hipSOLVER
      - hipSPARSE
      - hipTensor
      - llvm-project
      - MIOpen
      - MIVisionX
      - rccl
      - rdc
      - rocALUTION
      - rocBLAS
      - ROCdbgapi
      - rocFFT
      - ROCgdb
      - ROCK-Kernel-Driver
      - ROCm
      - rocm_bandwidth_test
      - rocm_smi_lib
      - rocm-cmake
      - ROCm-CompilerSupport
      - rocm-core
      - ROCm-Device-Libs
      - ROCm-Examples
      - rocminfo
      - rocMLIR
      - ROCmValidationSuite
      - rocPRIM
      - rocprofiler
      - rocr_debug_agent
      - rocRAND
      - ROCR-Runtime
      - rocSOLVER
      - rocSPARSE
      - rocThrust
      - roctracer
      - ROCT-Thunk-Interface
      - rocWMMA
      - rpp
      - Tensile
    default: 18
- type: textarea
  attributes:
    label: Steps to Reproduce
    description: (Optional) Detailed steps to reproduce the issue.
  validations:
    required: false
    
- type: textarea
  attributes:
    label: (Optional for Linux users) Output of /opt/rocm/bin/rocminfo --support
    description: The output of rocminfo --support could help to better address the problem.
  validations:
    required: false

- type: textarea
  attributes:
    label: Additional Information
    description: (Optional) Any additional information that is relevant, e.g. relevant environment variables, dockerfiles, log files, dmesg output (on Linux), etc.
  validations:
    required: false
